### ISSUE TITLE
Add popups to help the user understand the app

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda-in#110]
TT:
As funcionalidades já existentes deviam poder dispor de mensagens de ajuda. Visíveis, por exemplo, quando se passa o rato sobre os diferentes menus…

**Comment by adrapereira** [comment]
- [x] Add a question mark button which opens a popover with the help text when pressed
- [ ] Add a menu item to toggle the display of the help buttons
- [ ] Create a new ResourceBundle with the help texts
- [ ] Add help buttons wherever they're needed.

**Comment by luis100** [comment]
The popups (underlying library) are too slow and cumbersome, revert to using tooltips, that give a small text and point to the Help page. Put current text in the help page.
