### ISSUE TITLE
Unexpected exception with MS Access file

### ISSUE THREAD

**Issue by BorisDomajnko** [keeps/roda-in#126]
>java -Xmx1500m -Dfile.encoding=UTF-8 -jar dbptk-app-2.0.0-beta4.0.jar -i microsoft-access -if h:\APPL\DETEKTIVI\smucarji_2010.mdb -e siard-2 -ef out_smu1.siard

...
DEBUG 2016-03-31 09:53:11,365 (MsAccessUCanAccessImportModule) query: SELECT * FROM [PUBLIC].[Zaposlitve]
INFO 2016-03-31 09:53:11,708 (JDBCImportModule) 1000 rows processed
INFO 2016-03-31 09:53:12,035 (JDBCImportModule) 2000 rows processed
INFO 2016-03-31 09:53:12,347 (JDBCImportModule) 3000 rows processed
ERROR 2016-03-31 09:53:12,410 (Main) Unexpected exception
DEBUG 2016-03-31 09:53:12,441 (Main) Unexpected exception
java.lang.NullPointerException
	at com.databasepreservation.modules.msAccess.in.MsAccessUCanAccessImportModule.rawToCellSimpleTypeNumericApproximate(MsAccessUCanAccessImportModule.java:108)
--------------------------------------------------------------------------------------------------------------------
Table Zaposlitve has 9190 records. If I check the structure of this table:

INFO 2016-03-31 09:59:59,103 (JDBCImportModule) Check constraints were not imported: not supported yet on MsAccessUCanAccessImportModule
DEBUG 2016-03-31 09:59:59,103 (JDBCImportModule) Triggers were not imported: not supported yet on MsAccessUCanAccessImportModule
DEBUG 2016-03-31 09:59:59,103 (JDBCImportModule) count query: SELECT COUNT(*) FROM [PUBLIC].[Tipi_zahtevnosti]
DEBUG 2016-03-31 09:59:59,103 (JDBCImportModule) Counted 4 rows
DEBUG 2016-03-31 09:59:59,103 (JDBCImportModule) getting table structure for: Zaposlitve
DEBUG 2016-03-31 09:59:59,118 (JDBCImportModule) Getting structure of table PUBLIC.Zaposlitve
DEBUG 2016-03-31 09:59:59,118 (JDBCImportModule) Data type: 4
Type name: INTEGER
Column size: 32
Decimal digits: 0
Radix: 2
Remarks: null
Default value: null
Index: 1
Is Nullable: true
Is auto increment: true
Calculated type: SimpleTypeNumericExact
ColumnType hash: 1934331804

DEBUG 2016-03-31 09:59:59,118 (JDBCImportModule) Data type: 4
Type name: INTEGER
Column size: 32
Decimal digits: 0
Radix: 2
Remarks: null
Default value: 0
Index: 2
Is Nullable: true
Is auto increment: false
Calculated type: SimpleTypeNumericExact
ColumnType hash: 1934331804

DEBUG 2016-03-31 09:59:59,118 (JDBCImportModule) Data type: 4
Type name: INTEGER
Column size: 32
Decimal digits: 0
Radix: 2
Remarks: null
Default value: 0
Index: 3
Is Nullable: true
Is auto increment: false
Calculated type: SimpleTypeNumericExact
ColumnType hash: 1934331804

DEBUG 2016-03-31 09:59:59,118 (JDBCImportModule) Data type: 93
Type name: TIMESTAMP
Column size: 26
Decimal digits: 0
Radix: 0
Remarks: null
Default value: null
Index: 4
Is Nullable: true
Is auto increment: false
Calculated type: SimpleTypeDateTime
ColumnType hash: 159857490

DEBUG 2016-03-31 09:59:59,118 (JDBCImportModule) Data type: 93
Type name: TIMESTAMP
Column size: 26
Decimal digits: 0
Radix: 0
Remarks: null
Default value: null
Index: 5
Is Nullable: true
Is auto increment: false
Calculated type: SimpleTypeDateTime
ColumnType hash: 159857490

DEBUG 2016-03-31 09:59:59,118 (JDBCImportModule) Data type: 8
Type name: DOUBLE
Column size: 64
Decimal digits: 0
Radix: 2
Remarks: null
Default value: 0
Index: 6
Is Nullable: true
Is auto increment: false
Calculated type: SimpleTypeNumericApproximate
ColumnType hash: 1017775584

DEBUG 2016-03-31 09:59:59,118 (JDBCImportModule) Data type: 12
Type name: VARCHAR
Column size: 16777216
Decimal digits: 0
Radix: 0
Remarks: null
Default value: null
Index: 7
Is Nullable: true
Is auto increment: false
Calculated type: SimpleTypeString
ColumnType hash: 1423142621

DEBUG 2016-03-31 09:59:59,118 (JDBCImportModule) Data type: 93
Type name: TIMESTAMP
Column size: 26
Decimal digits: 0
Radix: 0
Remarks: null
Default value: 2016-03-31 09:59:58.0
Index: 8
Is Nullable: true
Is auto increment: false
Calculated type: SimpleTypeDateTime
ColumnType hash: 159857490

DEBUG 2016-03-31 09:59:59,118 (JDBCImportModule) Data type: 16
Type name: BOOLEAN
Column size: 0
Decimal digits: 0
Radix: 0
Remarks: null
Default value: null
Index: 9
Is Nullable: true
Is auto increment: false
Calculated type: SimpleTypeBoolean
ColumnType hash: 1332743696

INFO 2016-03-31 09:59:59,118 (JDBCImportModule) Check constraints were not imported: not supported yet on MsAccessUCanAccessImportModule
DEBUG 2016-03-31 09:59:59,118 (JDBCImportModule) Triggers were not imported: not supported yet on MsAccessUCanAccessImportModule
DEBUG 2016-03-31 09:59:59,118 (JDBCImportModule) count query: SELECT COUNT(*) FROM [PUBLIC].[Zaposlitve]
DEBUG 2016-03-31 09:59:59,118 (JDBCImportModule) Counted 9161 rows
DEBUG 2016-03-31 09:59:59,118 (JDBCImportModule) getting table structure for: PROP
DEBUG 2016-03-31 09:59:59,118 (JDBCImportModule) Getting structure of table UCA_METADATA.PROP
DEBUG 2016-03-31 09:59:59,118 (JDBCImportModule) Data type: 12

**Comment by adrapereira** [comment]
I believe this issue is in the wrong repository. You should report it here https://github.com/keeps/db-preservation-toolkit
