### ISSUE TITLE
Adding files to the "documentation" section is not working properly

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda-in#130]
Foram removidas as representações 2 e 3 e tentou-se repetir o processo. Desta vez a opção de arrastar pasta ou ficheiros para adicionar documentação não funcionou. Optou-se por fechar o Roda e repetir o processo desde o início. A referida opção voltou a não funcionar.

**Comment by adrapereira** [comment]
There is no bug here, there was probably a confusion with the documentation and data panes. Only the documentation pane allows the drop of files/folders and has no connection to the representations.

**Comment by jmaferreira** [comment]
André,

There was no confusing. Sometimes it just doesn’t work. You’ve seen it on my laptop.
