### ISSUE TITLE
Default templates fail to validate

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda-in#134]
Caro André,

O XML criado pelo template de EAD 2002 do RODA-in dá por omissão um XML inválido.

ValidationReport [valid=false, message=null, issues=[ValidationIssue [message=cvc-pattern-valid: Value '/' is not facet-valid with respect to pattern '(\-?(0|1|2)([0-9]{3})(((01|02|03|04|05|06|07|08|09|10|11|12)((0[1-9])|((1|2)[0-9])|(3[0-1])))|\-((01|02|03|04|05|06|07|08|09|10|11|12)(\-((0[1-9])|((1|2)[0-9])|(3[0-1])))?))?)(/\-?(0|1|2)([0-9]{3})(((01|02|03|04|05|06|07|08|09|10|11|12)((0[1-9])|((1|2)[0-9])|(3[0-1])))|\-((01|02|03|04|05|06|07|08|09|10|11|12)(\-((0[1-9])|((1|2)[0-9])|(3[0-1])))?))?)?' for type '#AnonType_normalam.date.normal'., lineNumber=27, columnNumber=34], ValidationIssue [message=cvc-attribute.3: The value '/' of attribute 'normal' on element 'unitdate' is not valid with respect to its type, '#AnonType_normalam.date.normal'., lineNumber=27, columnNumber=34]]]
 
O problema está aqui:

<unitdate normal="/">/</unitdate>

O atributo normal não pode ter este valor. É preciso mudar o template para não criar XML inválido.

Cumprimentos, 

Luis Faria
Innovation Director
KEEP SOLUTIONS, LDA.
Rua Rosalvo de Almeida, nº 5
4710-429 Braga, Portugal
W www.keep.pt E info@keep.pt 
T +351 253066735 F +351 253067248

**Comment by adrapereira** [comment]
Fixed in c222c18265cd86d909c83dd68fcc60ced37b3f4f.
