### ISSUE TITLE
Templates always overwritten on startup

### ISSUE THREAD

**Issue by luis100** [keeps/roda-in#135]
If templates are edited they are **always** overwritten on application startup, which defeats the purpose of having them there.

Instead of changing this behavior, write templates suffixed with ".sample" file extension. When loading a template, check if it exists in configuration and if not use the internal default one.

**Comment by adrapereira** [comment]
This is the expected behaviour, but you're right that it defeats the purpose of having them there.

I don't fully understand your proposal... I fell like that folder would start to be too confusing and with too many files.

Perhaps it's time to implement this #66.

**Comment by jmaferreira** [comment]
I wouldn’t go that far… Its easy enough to that folder and change the templates using a text editor.

However, a menu entry with a popup explaining that possibility would be very welcome.

To mitigate the clutter, why not adding some folders?

* config
* templates
* template-samples
* schemas
* log
* etc.

**Comment by adrapereira** [comment]
Yes, folders would be a good first step.

**Comment by adrapereira** [comment]
Fixed
