### ISSUE TITLE
Empty metadata values are sent to Mustache template

### ISSUE THREAD

**Issue by luis100** [keeps/roda-in#136]
When editing metadata in the form, if the a metadata value is filled and then emptied, an empty variable is sent to the mustache template which then doesn't cope well with mustache statements.

This seems to be done at DescriptionObject line 131, where values should only be added to the map if they are not blank (i.e. NULL, empty or all white spaces).

**Comment by adrapereira** [comment]
I couldn't reproduce this, but added some checks before the values are added to the map.
