### ISSUE TITLE
The fourth metadata import option is always disabled. Why?

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda-in#138]
![screen shot 2016-04-09 at 15 47 26](https://cloud.githubusercontent.com/assets/3181302/14404309/6d568ac0-fe6a-11e5-82f4-2f43aeb36ead.png)

**Comment by adrapereira** [comment]
It's disabled when you have at least one file selected as was requested by the client.

**Comment by jmaferreira** [comment]
If you take a closer look at the picture attached you may see that I have tens of folders selected.

**Comment by adrapereira** [comment]
And there's no file selected in the tree above what's in the picture?

**Comment by jmaferreira** [comment]
What are you talking about?!
I have selected several folders to be SIPs and I have all my metadata in a single folder (one file per SIP, matching the name of the SIP/folder). How to I do that if the option is disabled?

**Comment by adrapereira** [comment]
I thought we were talking about the 4th **association** option, sorry. Did you choose the 3rd association option in the previous panel?

**Comment by jmaferreira** [comment]
No. I choose the first one.

**Comment by adrapereira** [comment]
That's why then, it's only activated when you select the 3rd association option. I'll change it.

**Comment by jmaferreira** [comment]
Ok. There is really no reason why it shouldn’t be always on.
