### ISSUE TITLE
The templating system should support default values

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda-in#139]
Currently, when we put a variable in the template it is displayed on the metadata form with an empty value.

If we want to have a constant value, we can just fill in the value on the template XML.

But if we want to define a default value that the user will be able to change it is not possible. 

Suggestion:
```
<producer>{{Producer default="Miguel Ferreira"}}</producer>
```

Or some other default syntax that the moustache supports.

**Comment by luis100** [comment]
With  mustache syntax this would be done using inverted selections:

```
<producer>{{producer}}{{^producer}}Miguel Ferreira{{/producer}}</producer>
```

**Comment by luis100** [comment]
Also, we might want to replace Mustache with Handlebars, which is almost the same but with more built-in helpers, such as if-else, unless, with and others.

http://handlebarsjs.com/builtin_helpers.html

This would be a drop-in replacement as Mustache templates are a sub-set of Handlebars'.
http://jknack.github.io/handlebars.java/

**Comment by adrapereira** [comment]
Added in #153
