### ISSUE TITLE
The template system should be able to differentiate between auto-generated values and user variables

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda-in#140]
For example, currently the {{now}} variable is reserved for a auto date generator.

This are special value generators, not variable numbers. So, something like the following is essencial:

<date>{{Date default="Autovalue.now"}}</date>

Meaning that we should differentiate between the variable name (that is shown on the form as a label) and the value (which can be user input or auto generated by the app). Auto generated values should have a prefix such as "System." or "Autovalue.".

**Comment by luis100** [comment]
Mustache and Handlebars support scope, so you can add a namespace to the context that is sent to the template. Right now the context is a hashmap, but you can replace it with a more complex context like:

```
public class TemplateContext {
  public final Map<String,String> system;
  public final Map<String,String> user;
}
...
```

And then use them in the templates we can say:
```
{{user.date}}{{^user.date}}{{system.now}}{{/user.date}}
```

Please note that Mustache are **logic-less templates** so their functionality is quite limited. But Handlebars allow to create helpers which can be functions that receive any argument within the mustache var `{{#helper arg1 arg2}}` so we can extend the templating system with some functionalities if needed.
