### ISSUE TITLE
Digitaly sign the Windows executable

### ISSUE THREAD

**Issue by luis100** [keeps/roda-in#165]
When running the Windows .exe for RODA-in, it give a "Unknown Publisher" warning.

See this for a solution: http://stackoverflow.com/a/3109321/1987075

**Comment by luis100** [comment]
Check this on how to get a code signing certificate: https://msdn.microsoft.com/en-us/library/windows/hardware/hh801887(v=vs.85).aspx

Also, signtool documentation is here: https://msdn.microsoft.com/en-us/library/windows/desktop/aa387764(v=vs.85).aspx

**Comment by adrapereira** [comment]
Abandoned due to costs.
