### ISSUE TITLE
When adding external EAD its XSD schema is not added to the package

### ISSUE THREAD

**Issue by GregorARS** [keeps/roda-in#179]
We create our own EAD3 file externaly (ead3.xml), and after we use the "One description item with all selected files and/or folders" option, we add it using "Load from a single file" option. 
After creating the zip file, the accompanying XSD file (ead3.xsd), which lies in the same folder, and has the same name is not added to the Schemas folder and therefore results in an error when validating the SIP in EarkWeb. 
Since we can not add the xsd file to the schemas manualy (nor would we like to), can you enable the software to demand such a file and/or at least enable its addition to the SIP package?

**Comment by adrapereira** [comment]
Hi @GregorARS, when choosing the "Load from a single file" metadata option, if you choose the EAD3 type the application should add the correct schema to the SIP. It won't add the schema that accompanies the XML metadata file, it will add the ead3.xsd schema from your `{home folder}/roda-in/schemas` folder.

![untitled](https://cloud.githubusercontent.com/assets/4313971/17782468/8382b5f4-656b-11e6-9516-aa027573b3cc.png)

**Comment by GregorARS** [comment]
Hi @adrapereira I am using Roda-In version rodain-app-2.0.0-alpha.7.3. I did as you suggested. I have the ead3.xsd in my /roda-in/schemas folder, 
![image](https://cloud.githubusercontent.com/assets/20597844/17810839/c3d73120-661f-11e6-98f8-c7b2ee6a06e5.png)
but it did not end up in the package, there are only mets and xlink xsd's:
![image](https://cloud.githubusercontent.com/assets/20597844/17810871/f02dcb08-661f-11e6-948a-63274b0cb9e2.png)

**Comment by adrapereira** [comment]
Hi @GregorARS, it was indeed a problem of the application. I will be publishing a new version of RODA-in later this week, but if this is an urgent issue I can send you a version sooner.
