### ISSUE TITLE
The help balloons strategy should be rethought

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda-in#192]
Erroneous situations:
* overlap with other information
![captura de ecra de 2016-09-08 12 49 30](https://cloud.githubusercontent.com/assets/1315759/18348354/d4628a50-75c2-11e6-92bb-ca78a7442123.png)

* not disappearing when they should (e.g. the associated function has been already executed & finished)
![captura de ecra de 2016-09-08 12 50 13](https://cloud.githubusercontent.com/assets/1315759/18348357/d905dd0a-75c2-11e6-88a7-2f4939749ec5.png)

roda-in version: 3a8f5c2f4d777fcba9d831dac93f14f094d23bfc

**Comment by jmaferreira** [comment]
If you can’t manage to make the help popups work correctly, just remove them altogether.
