### ISSUE TITLE
Produce an Inventory Report while creating SIPs (CSV)

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda-in#199]
Checksums and all the other stuff should be obtained from the SIP it self and not recalculated.

**Comment by sleroux-keep** [comment]
For EARK Sip, the report is done. 
For the Bagit, the report is missing the file size (the Bag hava a method "getFile(XXX).getSize()", but the return value is always 0... I need to extend the bag to keep the paths of the original files...

**Comment by sleroux-keep** [comment]
Added file size on bagit report... 

The only thing missing is the "original file" path... The SIP keeps this "value"... BagIt doesn't...

**Comment by jmaferreira** [comment]
Done.
