### ISSUE TITLE
There is a field that appears 3 times on the UI

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda-in#208]
Check RODA template to see if this also happens

![screen shot 2016-10-18 at 14 50 41](https://cloud.githubusercontent.com/assets/3181302/19480454/5262773c-9542-11e6-8a69-06000e03a748.png)

**Comment by sleroux-keep** [comment]
Template issue. Fixed.

**Comment by jmaferreira** [comment]
Fixed.
