### ISSUE TITLE
Erro ao selecionar um item na árvore do explorador de ficheiros

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda-in#209]
![screen shot 2016-10-19 at 23 25 25](https://cloud.githubusercontent.com/assets/3181302/19539823/758cb30a-9653-11e6-95ec-3b05788c87cb.png)

null
    org.roda.rodain.source.ui.FileExplorerPane.lambda$updateAttributes$5(FileExplorerPane.java:351)
    java.lang.Iterable.forEach(Iterable.java:75)
    org.roda.rodain.source.ui.FileExplorerPane.updateAttributes(FileExplorerPane.java:351)
    org.roda.rodain.source.ui.SourceClickedEventHandler.handle(SourceClickedEventHandler.java:46)
    org.roda.rodain.source.ui.SourceClickedEventHandler.handle(SourceClickedEventHandler.java:18)
    com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    javafx.event.Event.fireEvent(Event.java:198)
    javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3470)
    javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3398)
    javafx.scene.Scene$MouseHandler.process(Scene.java:3766)
    javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
    javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
    javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
    com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:380)
    com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:294)
    java.security.AccessController.doPrivileged(Native Method)
    com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:416)
    com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
    com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:415)
    com.sun.glass.ui.View.handleMouseEvent(View.java:555)
    com.sun.glass.ui.View.notifyMouse(View.java:937)

**Comment by sleroux-keep** [comment]
I can't reproduce this issue...

**Comment by jmaferreira** [comment]
Oh well..
