### ISSUE TITLE
RODA-in creates invalid SIP due to weird filename

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda-in#210]
Cause:
'file:data/1__#$!@%!#__unknown.jpg' is not a valid value for 'anyURI'.]

This SIP was created with the latest version of RODA-in (the 19h one). 

Example files attached.

[data.zip](https://github.com/keeps/roda-in/files/540465/data.zip)

```
Is the package valid?no
INFOMETS.xmlMain METS.xml file was found.
INFOMETS.xmlMain METS.xml file is valid.
INFOMETS.xmlMain METS.xml file has E-ARK structural map.structMap with id 'IDC0C82AA1-E3C3-4A1F-867B-F1040B90608D'
INFOmetadata/descriptive/ead.xmlDescriptive metadata file was found and file checksum matches METS checksum.
INFOrepresentations/rep1/METS.xmlRepresentation METS.xml file was found.
ERRORrepresentations/rep1/METS.xmlRepresentation METS.xml file is not valid.javax.xml.bind.UnmarshalException
 - with linked exception:
[org.xml.sax.SAXParseException; systemId: file:/usr/local/tomcat/temp/mferreira%20-%20ID667e01c1-46c2-4d0c-9144-4ab27898c321/representations/rep1/METS.xml; lineNumber: 13; columnNumber: 111; cvc-datatype-valid.1.2.1: 'file:data/1__#$!@%!#__unknown.jpg' is not a valid value for 'anyURI'.]
WARNMETS.xmlNo representations were found in main METS.xml file.div with id 'IDCC24C4B2-DBED-4311-BB8C-0F9FE12F3D8E'
INFOschemas/mets.xsdSchema file referenced in METS.xml was found and file checksum matches METS checksum.
INFOschemas/xlink.xsdSchema file referenced in METS.xml was found and file checksum matches METS checksum.
```

**Comment by sleroux-keep** [comment]
Commons-IP issue. 
Issue created at: https://github.com/keeps/commons-ip/issues/14
Fixed @ https://github.com/keeps/commons-ip/commit/4b30fc678d21f9ad6101f3aa5d4329a47a12737f

**Comment by jmaferreira** [comment]
@sleroux-keep  who should do this? "needs to add the alpha-22 to artifactory"

**Comment by hsilva-keep** [comment]
That was already fixed by @sleroux-keep in commons-ip repo & I've deployed alpha22 into artifactory.

**Comment by sleroux-keep** [comment]
Deployed bu @hsilva-keep 

http://artifactory.keep.pt/webapp/browserepo.html?pathId=keep%3Aorg%2Froda-project%2Fcommons-ip%2F1.0.0-alpha22

**Comment by jmaferreira** [comment]
I guess this is fixed given the amount of eyes on top of the issue.
