### ISSUE TITLE
Add a tooltip to the options MIXED, SMURF, RDB, etc.

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda-in#214]
The tooltip should read something on the line of:
- Use the SIP type MIXED when the contents of the package include various media types. 
- Use the SIP type RDB when the contents of the package consist of a relational database.
- Use the SIP type SMURF when the contents of the package consist of Semantically marked up records, i.e. records extracted from a Electronic Records Management System.

**Comment by sleroux-keep** [comment]
Translations updated @ 5e92e41efc15900fe0de836aeebb669208e65bd8 (the IPType is based on commons-ip... commons-ip was updated and the translation file for roda-in was not.)

**Comment by jmaferreira** [comment]
Done.
