### ISSUE TITLE
Change translations

### ISSUE THREAD

**Issue by sleroux3386** [keeps/roda-in#221]
Export > Create SIP(s)
Inspection > Inspector
Drop files/folders to add documentation > Drag files/folders from File Explorer to add documentation
Source file explorer > File explorer
description item > information package
Classification scheme > Information packages (only on column header)

Add numbers to column headers

**Comment by sleroux-keep** [comment]
Fixed @ 608c7ef2a7c892f69f2f9303ce77519aca5b9e4d

**Comment by jmaferreira** [comment]
Done.
