### ISSUE TITLE
When 2 packages have a single "Key-Value" metadata file we cant do multiple editing of metadata

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda-in#227]
It works fine for EAD and DC.
When SIPs have more than one format it is also not possible (but I guess this is deliberate).

![screen shot 2016-12-23 at 11 27 09](https://cloud.githubusercontent.com/assets/3181302/21453004/002bfaf2-c903-11e6-89c4-d0ead41c18da.png)

**Comment by sleroux-keep** [comment]
Fixed @ 2105dd9bfb101319dff1e8a077de2d29060bb032

When the metadata are different, it's not possible no "multiple edit".

**Comment by jmaferreira** [comment]
Fixed.
