### ISSUE TITLE
The creation of SIPs get slower and slower as the process progresses

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda-in#228]
As little as 1500 is sufficient to see the problem. Adding each file takes longer and longer and the process takes over 30 minutes just to create 1 SIP with 1500 files in it.

File sizes were all about the same size ~10MB each (MP3 collection).

The total size of the SIP is estimated to be 10 GB.

**Comment by sleroux-keep** [comment]
When trying to reproduce, i get no performance issue...

I've tested with a folder, with 60 folders insides (total of 1400 files, 8.2GB).

When creating information package (using the option "One IP for each selected folder"), the process takes 6 seconds. It creates a single sip, with the data i've selected as "Rep1".

When creating the SIP, the files are added sequencially, at a fixed rate (2.4 files / seconds). I've created a log with the rate from the start of the process to the end... 2.4 files/s, 2.3 files/s, 2.5 files/s, 2.4 files/s, ... 

Can you give more "information" to reproduce this issue?

**Comment by sleroux-keep** [comment]
Tests:
Corpora: Folder, with 60 sub-folders (total of 1500 files; 8GB) on HDD (not SSD)

Creating SIP on HDD: 9min 51s (single SIP; 8GB)
Creating SIP on SSD: 9min 10s (single SIP; 8GB)
Creating ZIP (command line) on HDD: 6min 49s
Creating ZIP (command line) on SSD: 6min 23s

In all cases, the "rate" at which the files are added is "stable" (no performance issues)

**Comment by jmaferreira** [comment]
I test it again in my machine.

**Comment by jmaferreira** [comment]
On macOS the problem still stands.

**Comment by jmaferreira** [comment]
Tests reveal that the progress is linear.
