### ISSUE TITLE
Crash when moving mouse

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda-in#229]
null
	org.roda.rodain.inspection.trees.SipDataTreeView.lambda$new$0(SipDataTreeView.java:43)
	com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	javafx.event.Event.fireEvent(Event.java:198)
	javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3470)
	javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3398)
	javafx.scene.Scene$MouseHandler.process(Scene.java:3766)
	javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:380)
	com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:294)
	java.security.AccessController.doPrivileged(Native Method)
	com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:416)
	com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:415)
	com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	com.sun.glass.ui.View.notifyMouse(View.java:937)

**Comment by sleroux-keep** [comment]
Need steps to reproduce this issue...

**Comment by jmaferreira** [comment]
Lets stay sharp
