### ISSUE TITLE
When we select folders and a file we can't select association option 4

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda-in#231]
![screen shot 2017-01-06 at 15 55 43](https://cloud.githubusercontent.com/assets/3181302/21723519/a6e10c86-d428-11e6-87e3-4041beb93a4b.png)

**Comment by sleroux-keep** [comment]
Fixed @ 237f7edb25fa02583d6e7eda2cf85097b161496b 

When selecting files, SIP are created with a single file (single item classification scheme)

**Comment by jmaferreira** [comment]
ok
