### ISSUE TITLE
When a date is inserted in one SIP, selecting various SIPs on the middle column produces an error

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda-in#232]
![screen shot 2017-01-06 at 16 02 37](https://cloud.githubusercontent.com/assets/3181302/21723760/92c8b61c-d429-11e6-8def-d521a4c21578.png)
Text '{{mixed}}' could not be parsed at index 0
	java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
	java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1777)
	javafx.util.converter.LocalDateTimeStringConverter$LdtConverter.fromString(LocalDateTimeStringConverter.java:208)
	javafx.util.converter.LocalDateStringConverter.fromString(LocalDateStringConverter.java:134)
	org.roda.rodain.inspection.InspectionPane.createFormDatePicker(InspectionPane.java:784)
	org.roda.rodain.inspection.InspectionPane.updateForm(InspectionPane.java:598)
	org.roda.rodain.inspection.InspectionPane.lambda$createMetadataTop$5(InspectionPane.java:379)
	com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:361)
	com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	javafx.beans.property.BooleanPropertyBase.fireValueChangedEvent(BooleanPropertyBase.java:103)
	javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
	javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	javafx.scene.control.ToggleButton.setSelected(ToggleButton.java:149)
	javafx.scene.control.ToggleButton.fire(ToggleButton.java:255)
	org.roda.rodain.inspection.InspectionPane.showMetadataPane(InspectionPane.java:2019)
	org.roda.rodain.inspection.InspectionPane.lambda$updateSelectedMetadata$40(InspectionPane.java:1516)
	com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	javafx.event.Event.fireEvent(Event.java:198)
	javafx.concurrent.EventHelper.fireEvent(EventHelper.java:219)
	javafx.concurrent.Task.fireEvent(Task.java:1356)
	javafx.concurrent.Task.setState(Task.java:723)
	javafx.concurrent.Task$TaskCallable.lambda$call$500(Task.java:1434)
	com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	java.security.AccessController.doPrivileged(Native Method)
	com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
![screen shot 2017-01-06 at 16 01 42](https://cloud.githubusercontent.com/assets/3181302/21723720/706a3898-d429-11e6-9e9c-8d638bc6b4f6.png)

**Comment by sleroux-keep** [comment]
Fixed @ 50fee9b057a253259cdef91aedea4921a2aa111c

Note: When using multiple-edit, I can't place a {{mixed}} value in the DatePicker... Currently, I instantiate the DatePicker empty...

**Comment by jmaferreira** [comment]
Ok.
