### ISSUE TITLE
Layout issue

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda-in#233]
Can we fix this by limiting the min-width of the right most item? The middle section should adjust automatically.

![screen shot 2017-01-06 at 17 00 39](https://cloud.githubusercontent.com/assets/3181302/21725790/c48dcb44-d431-11e6-9ad6-02ef8ee947e0.png)

**Comment by sleroux-keep** [comment]
Added min-width to type label (60) @ d24b1f5c0ed83a145139f72a2202f527b3670fd1

**Comment by sleroux-keep** [comment]
Updated @ 7f9a49a5e0311975cd86fe834e1fd7aca059f2ba (min-width moved to CSS)

**Comment by jmaferreira** [comment]
Fixed.
