### ISSUE TITLE
Roda-in keeps alerting for new version

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda-in#234]
![screen shot 2017-01-17 at 20 03 20](https://cloud.githubusercontent.com/assets/3181302/22058025/556194bc-dd5f-11e6-8abe-9ae6b9fc4723.png)

**Comment by sleroux-keep** [comment]
Fixed

**Comment by jmaferreira** [comment]
Beta 2 didn't warn me about anything.

**Comment by jmaferreira** [comment]
Now fixed.
