### ISSUE TITLE
Output directories with underscores don't show up on button text

### ISSUE THREAD

**Issue by luis100** [keeps/roda-in#235]
When creating SIPs, if a folder with a name with an underscore is selected as the output directory, the underscore doesn't show up on the selection button text.

**Comment by sleroux-keep** [comment]
https://docs.oracle.com/javase/8/javafx/api/javafx/scene/control/Labeled.html#setMnemonicParsing-boolean-
MnemonicParsing property to enable/disable text parsing. If this is set to true, then the Label text will be parsed to see if it contains the mnemonic parsing character '_'. When a mnemonic is detected the key combination will be determined based on the succeeding character, and the mnemonic added.

The default value for Labeled is false, but it is enabled by default on some Controls. 

And MnemonicParsing is enable by default for the JAVA FX Button:

http://grepcode.com/file/repo1.maven.org/maven2/net.java.openjfx.backport/openjfx-78-backport/1.8.0-ea-b96.1/javafx/scene/control/Button.java#97

Added setMnemonicParsing(false) after button construction fixes this issue.

Fixed @ 1d411f448028cac5befad951ddc4a1dcd4df0ebe

**Comment by jmaferreira** [comment]
Do you know if this has been merges yet?

**Comment by hsilva-keep** [comment]
I was checking if this issue has been solved already at this precise moment :) Damn. I'll answer to that in a minute.

**Comment by jmaferreira** [comment]
You should train your trigger speed! :)

**Comment by hsilva-keep** [comment]
Running code from last commit in master branch (ccbb39734f48c62d9d55d76572360e347ce41943), I have confirmed that this issue no longer occurs.
![issue](https://cloud.githubusercontent.com/assets/1315759/24155265/40b3ba32-0e4b-11e7-94da-18744bd4880e.png)
