### ISSUE TITLE
When we use the automatic association of metadata the Sip (previously known as DescriptionObject) attributes (id, title, etc.) are not being updated

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda-in#243]
This makes an inconsistent behaviour between SIPs that have been inspected and SIPs that haven't being inspected on the UI. The file names of the exported SIPs are different in both cases.

**Comment by nunovieira220** [comment]
Solved on 929917e9c69abfed1bf1872e50cc091230172344. @hsilva-keep please confirm it.

**Comment by hsilva-keep** [comment]
It is nice ok.
