### ISSUE TITLE
The "Create SIP(s)" window should preserve its options between executions of the application

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda-in#245]
Store state on config file.

![screen shot 2017-03-19 at 14 39 18](https://cloud.githubusercontent.com/assets/3181302/24081789/fc21935c-0cb1-11e7-8436-99deed952241.png)

**Comment by hsilva-keep** [comment]
Both [ConfigurationManager.getAppConfig()](https://github.com/keeps/roda-in/blob/master/src/main/java/org/roda/rodain/core/ConfigurationManager.java#L563) & [ConfigurationManager.setAppConfig()](https://github.com/keeps/roda-in/blob/master/src/main/java/org/roda/rodain/core/ConfigurationManager.java#L552) must be used.

**Comment by chalkos** [comment]
first approach done on 0801e31db81fbd2546e3bb9373e539fef91e90a6 with a few tweaks between that and ebaf477ff563f3e4976bd6b8de0bc190fc4e51d2, which completed the feature for the METS Header window.
