### ISSUE TITLE
Add support to new SIP format

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda-in#248]
The graphical user interface (GUI) of the application should display a new option under “SIP
format” when the user selects the “Create SIP(s)” option.
The combo box should include an additional value called “Hungarian SIP 4”.

![t1](https://cloud.githubusercontent.com/assets/1315759/24153172/9bf3b0a6-0e45-11e7-9eba-464ff130f41e.png)

Hungarian SIP creation logic will be done in [Commons-IP](https://github.com/keeps/commons-ip/issues/22).

**Comment by hsilva-keep** [comment]
@jmaferreira this issue will be done by @nunovieira220 and not by @chalkos. If I remember correctly, we have decided that "view" is done essentially by @chalkos & "model/controller" by @nunovieira220. And this issue, besides adding the new option to the dropbox shown in the image above, is all about supporting the new SIP format. Right?

**Comment by jmaferreira** [comment]
Correct.

**Comment by jmaferreira** [comment]
Maybe an additional issue for the UI should be created?

**Comment by hsilva-keep** [comment]
@jmaferreira There's no need for that, @nunovieira220 knows precisely what he needs to do (also adding that new element to the combobox).

This task also relates to  #251.

**Comment by nunovieira220** [comment]
Backend support added on 8ecd5f1872d091971e0324f18d74ebbea8226fff

**Comment by hsilva-keep** [comment]
Done.
