### ISSUE TITLE
Add new form to fill in the METS Header

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda-in#249]
The "Hungarian SIP 4" contains information under the <metsHdr> section of the METS file
that is specific to each producer organisation.
If the “Hungarian SIP 4” format is selected, when the “Start” button is selected, a new pop
window should be shown that allows the user to provide all the attributes that the Hungarian
SIP specification requires. The attributes and their cardinality are described in the table beneath. Also, these attributes shall be saved in a local configuration file to be reused the next time the application is used to create SIPs.
Please note that, whenever possible, the attributes may be automatically generated by the
application and confirmed by the user before creating SIPs.

Additionally, this metadata panel should also be shown when the E-ARK SIP type is selected. This will have an impact on the UI and also on the [Common-
IP Java Library](https://github.com/keeps/commons-ip).

### Commons-IP

An issue was created to create [Header information abstraction (#23).](https://github.com/keeps/commons-ip/issues/23)

### METS header attributes

Consult internal document, "D1 - Requirements specification-0.2.pdf" , Table 1, skipping the first 3 rows.

**Comment by chalkos** [comment]
Completed on ebaf477ff563f3e4976bd6b8de0bc190fc4e51d2

**Comment by hsilva-keep** [comment]
It has been decided that, ATM, RODA-in will not show the METS Header form when the SIP format is E-ARK. If one wants to have it, one has to configure it in config.properties.

**Comment by hsilva-keep** [comment]
Done.
