### ISSUE TITLE
Add new file naming pattern

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda-in#250]
RODA-in already supports the definition of file naming patterns. The Hungarian SIP
specification defines how the SIP files should be named. RODA-in should be enhanced to
support one additional pattern that complies with the Hungarian SIP specification.
More information about naming & compressions scheme is described beneath.

When the “Hungarian SIP 4” option is selected on the SIP format combo box, the SIP file
name pattern should be preselected automatically. In this case, the user should not be able
to change the pattern.
More, in the file name pattern there is a Sequence number that should be kept be the
application. This number should start on 001 and be maintained for future use. However,
the user should be free to change the current value of the counter.
![t3](https://cloud.githubusercontent.com/assets/1315759/24154205/6fafd8e6-0e48-11e7-868c-79da1d5298b9.png)

### Naming & compressions scheme

The SIP should be packaged as a standard ZIP64 uncompressed file with the following
naming scheme:
```SIP_[DELIVERYDATE]_[TRANSFERRING]_[SERIALNUMBER].zip```
Each of the previous variables are described next:

- The SIP filename always begins with “SIP_”.
- [DELIVERYDATE] - the date of transfer as YYYYMMDD
- [TRANSFERRING] - abbreviation of the name of the transferring organization (e.g. MEH, KIM, KSH). f there is no official abbreviation, then a short expression to designate the organization should be selected.
- [SERIALNUMBER] - the submission number within a transfer batch starting at 001.
An example is:
SIP_20131201_KSH_001.zip

**Comment by chalkos** [comment]
Fixed on a70348bc8d171258ffb883f3405f716301d0f1bd

**Comment by hsilva-keep** [comment]
Check.
