### ISSUE TITLE
Add the ability to create the manifest file

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda-in#251]
The Hungarian SIP specification defines that next to the SIP file itself there should be a
manifest file with the same name as the SIP but with the .TXT extension.
When the “Hungarian SIP 4” format is selected on the application, the .TXT files should be
automatically created and placed on the same folder where the rest of the SIPs are being
created.
More information about the manifest file can be found on section beneath.

### Manifest file

Consult internal document, "D1 - Requirements specification-0.2.pdf", section "THE MANIFEST".

**Comment by nunovieira220** [comment]
Added on 8ecd5f1872d091971e0324f18d74ebbea8226fff
