### ISSUE TITLE
Add a specific help page in Hungarian

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda-in#252]
The Help of the application should be updated to provide information on how to create
Hungarian SIPs. Such documentation will be provided in English, that will be later on kindly translated to Hungarian by the National Archives of Hungary.

**Comment by jmaferreira** [comment]
Add section to explain both of these features

![screen shot 2017-05-10 at 11 50 25](https://cloud.githubusercontent.com/assets/3181302/25895213/eb11910a-3576-11e7-88ce-21ba8adaac69.png)
![screen shot 2017-05-10 at 11 50 20](https://cloud.githubusercontent.com/assets/3181302/25895214/eb3b18a4-3576-11e7-82d0-711a9072d9e3.png)

**Comment by jmaferreira** [comment]
The page you sent me to review is the EN version. There must exist a Hungarian version that contains all the Hungarian specifics as the title of this ticket entails. Assuming that the version you sent me is the right  one, here are my comments:

- There no mention of the 3rd format that the tool supports in the **Supported SIP formats** section, i.e. the Hungarian SIP 4. We have talked about it this morning!
- The link to the E-ARK SIP specification should be updated to http://www.dasboard.eu/specifications/sip
- There should be a paragraph explaining that now there are two different releases of the tool, the Normal and the Hungarian. Explain the diferences. This could actually be a new section right after the introduction.

After adding this changes to the html file, don't forget to copy the file to a new version in Hungarian (even though the page is in English). **This is a project deliverable and should not be forgotten.**
