### ISSUE TITLE
Add a possibility to name a representation folder

### ISSUE THREAD

**Issue by GregorARS** [keeps/roda-in#254]
In current Roda-In representations are automaticaly namet rep1, rep2.... etc. What we would need is to have a possibility to rename the representation to something else.

**Comment by nunovieira220** [comment]
It is now possible to rename representations since 0a78c3dc62f19dc4b6f836090b3e0a84207ebfae. @hsilva-keep please confirm it.

**Comment by hsilva-keep** [comment]
Check.
