### ISSUE TITLE
When we import a classification plan from RODA, their nodes are marked as "Documentation" and should be EAD 2002

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda-in#268]
![screen shot 2017-04-19 at 14 00 08](https://cloud.githubusercontent.com/assets/3181302/25181200/aa4610e8-2508-11e7-880b-fb730858466b.png)

**Comment by chalkos** [comment]
The problem: the metadata type of "documentation" is `ead`, which is the same metadata type of the "ead2002".

When going through the configuration, after finding out that the type as `ead` and metadata name as `ead2002`, the application would find another metadata name for the same type (type `ead`, name `documentation`) and use that one.

Solution: stop looking for another metadata when a match is found (this way the application stops looking after finding `ead2002`).
