### ISSUE TITLE
When we create a new project there are still evidences of the previous one

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda-in#271]
To reproduce:

- Add a few items to the middle section
- Remove some
- Export them all
- Create new project
- Hit Create SIPs and see how many SIPs it generates (it should be zero, its a new project)

**Comment by chalkos** [comment]
I followed the steps but in my case it did not create any SIPs after creating the new project.

**Comment by jmaferreira** [comment]
You have to use the application for a while… REALLY USE IT to create SIPs and not just dick around with small tests.

**Comment by chalkos** [comment]
Ok.

Meanwhile if you come up with a deterministic way to reproduce the issue, let me know.

**Comment by jmaferreira** [comment]
Don’t close the issue this way…

Create a few SIPs… 
Export them
Create some more
Export them
New project
Export

**Comment by jmaferreira** [comment]
We couldn't reproduce this at this point. We'll close it.
