### ISSUE TITLE
On the portuguese help fix the following translations

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda-in#273]
1. painél > painel
2. raíz > raiz
3. Este objetos > Estes objetos
4. reflectir > refletir
5. Os ficheiros adicionados à documentação não altera > Os ficheiros adicionados à documentação não alteram
6. no botão,um novo  > no botão, um novo 
7. items de descrição > itens de descrição
8. Isto acontece pois pacotes não podem  > Isto acontece porque os pacotes não podem 
9. sub-árvore > subárvore 
10. com um seleccionador de data > com um selecionador de data

**Comment by chalkos** [comment]
1. not found
2. ok
3. ok
4. not found
5. not found
6. ok
7. ok
8. found similar string with "SIPs" instead of "pacotes"
9. ok
10. ok

**Comment by jmaferreira** [comment]
Look harder!

![screen shot 2017-04-21 at 07 57 55](https://cloud.githubusercontent.com/assets/3181302/25266217/4f93bca2-2668-11e7-958c-60ad636ecd41.png)

**Comment by chalkos** [comment]
I did, and found the remaining translations :)
