### ISSUE TITLE
Hungarian SIPs failed to be ingested in Preservica due the paths being URL encoded in the METS.

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda-in#277]
We analyzed the log file of the SDB which was created during the ingest of the RODA-in SIP. We found, that there is no problem with having files in a multi-level folder structure. So there is no need to change the way RODA-In stores files in multi-level folder structure.

The problems are that certain carachters are coaded differently in the two systems.

Original text from metadata.XML of the SIP created by RODA-In:
...
```
           <file ID="uuid-D7113342-5F2E-42D5-9592-6FF693937643" MIMETYPE="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" SIZE="427126" CREATED="2017-04-26T14:00:59.625+02:00" CHECKSUM="877EAFD1123272BD6792650743603EBDF914BC7C5CA125B09B98EF7D96862E8D" CHECKSUMTYPE="SHA-256">
               <FLocat LOCTYPE="URL" xlink:type="simple" xlink:href="data%2Frep1%2FTorzskonyv%2FXLS%2FHU-BFL_Torzskonyvi_nyilvantart%C3%A1s_2015.xlsx"/>
           </file>
```

Modified text from metadata.XML of the SIP created by RODA-In:
...
```
           <file ID="uuid-D7113342-5F2E-42D5-9592-6FF693937643" MIMETYPE="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" SIZE="427126" CREATED="2017-04-26T14:00:59.625+02:00" CHECKSUM="877EAFD1123272BD6792650743603EBDF914BC7C5CA125B09B98EF7D96862E8D" CHECKSUMTYPE="SHA-256">
               <FLocat LOCTYPE="URL" xlink:type="simple" xlink:href="data\rep1\Torzskonyv\XLS\HU-BFL_Torzskonyvi_nyilvantartás_2015.xlsx"/>
           </file>
```

1. It is problem that for the "\" is coded by "%2F"
2. The other problem is caused by special hungarian characters in the file names: e.g: having "%C3%A1" instead of "á".

Is it possible to change the encoding of these special characters in the matadata.xml file? Is there some special requirement to encode these characters in that way?

Examples attached:

[Archive.zip](https://github.com/keeps/roda-in/files/989549/Archive.zip)

**Comment by nunovieira220** [comment]
This issue should be fixed. The path encoding was removed on commons-ip and the METS is still valid.

**Comment by jmaferreira** [comment]
Did you escape the tokens? e.g.: token/token/token

**Comment by hsilva-keep** [comment]
@jmaferreira as stated  in the comment above, the encode was completely removed (as we have decided last f2f meeting).

**Comment by jmaferreira** [comment]
@luis100, is this a good idea?

**Comment by luis100** [comment]
I think we should at the least how it copes with filenames with special XML
characters like `"'?&<>`.

Em 15/05/2017 17:27, "Miguel Ferreira" <notifications@github.com> escreveu:

@luis100, is this a good idea?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/keeps/roda-in/issues/277#issuecomment-301528234>, or mute
the thread
