### ISSUE TITLE
Add a small visual metaphor (+) to the links bellow the METS sections

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda-in#281]
It should display something like: 

(+) Add Submission number

**Comment by chalkos** [comment]
@jmaferreira What if I add a button on the right side and align the text to the right? Clicking either the text or the button would add a new field

**Comment by chalkos** [comment]
proposed solution in branch bf-alt-fix-281:

![roda-in-buttons-right](https://cloud.githubusercontent.com/assets/98429/25901117/a01575e2-358d-11e7-8a54-5174b17c53de.png)

**Comment by chalkos** [comment]
proposed solution in branch bf-fix-281:
![roda-in-button-left](https://cloud.githubusercontent.com/assets/98429/25902027/440f130e-3590-11e7-9988-5dc5d035dd72.png)

**Comment by chalkos** [comment]
@jmaferreira choose one :)

**Comment by jmaferreira** [comment]
Definitely the later.
