### ISSUE TITLE
Status and Transfer type are saved with default values without showing them on the screen.

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda-in#284]
Always display them on the screen.

**Comment by chalkos** [comment]
@jmaferreira 
My commit makes roda-in do what is asked in this issue, but the transfer type was already always being shown on screen. Maybe we misunderstood something?

**Comment by jmaferreira** [comment]
In my testes it appeared closed by default. Do you confirm?

**Comment by chalkos** [comment]
@jmaferreira makes no difference anymore, because #286 asks to make it a constant and remove it from the form.

**Comment by jmaferreira** [comment]
Hmm… that’s odd. Check the original email please. It could be my mistake.

**Comment by chalkos** [comment]
From the email:

> There are issues with mandatory fields:
> * (...)
> * Status and Transfer type are saved with default values without showing them on the screen.

and also

> The ’Transfer type’ is unnecessary in the form, it has a constant value in SIP 4: „STRUKTURÁLATLAN”.

So there seems to be an inconsistence.

----------

I checked the METS Header translations docx, and the field has the description

> Type of the transfer can be certified ERMS represented as „TANÚSÍTOTT IKTATÁS”; ERMS, represented as „STRUKTURÁLT IKTATÁS”; business system with record level metadata, represented as „STRUKTURÁLT IRATNYILVÁNTARTÁS”; high level metadata, represented as
„STRUKTURÁLATLAN”.

But there is also a comment stating:

> Constant value for package type 4: „STRUKTURÁLATLAN”

-------

So in conclusion it seems that not showing the field and always adding it (when creating hungarian SIP 4) with value of `STRUKTURÁLATLAN` is the right way to handle this.
