### ISSUE TITLE
METS Header form should be included also in EARK SIPs.

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda-in#285]
Only on the Hungarian release.

**Comment by chalkos** [comment]
This should also include a way to make 2 separate JAR files:

* general use release
* hungarian release (the only difference at the moment being the that the METS Header form is active by default for EARK SIPs).

**Comment by chalkos** [comment]
Closed via https://github.com/keeps/roda-in/commit/1d6134f777ca2e97546bd3f3d5cb756c9f3dbd18
