### ISSUE TITLE
Update resources on transifex 

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda-in#287]
Send resources that need translation to Zoltan before closing the version.

**Comment by chalkos** [comment]
@luis100 I will need your help on this. I noticed that the RODA-in translations only use the english file (see https://www.transifex.com/roda-1/roda-in/content/ where there are only 2 resource files and both are for the english language) which does not seem correct.

Maybe you could explain the main decisions related to transifex in roda-in, and if the current roda-in (transifex) implementation can be improved.

**Comment by luis100** [comment]
English is the main language, if you click the file you'll see all the languages is translated to:
https://www.transifex.com/roda-1/roda-in/lang_enproperties/

I recommend installing [transifex CLI](https://docs.transifex.com/client/introduction) and sincronize with the server (but first backup all online translations).

**Comment by luis100** [comment]
The backups: 
[roda-in_lang_enproperties_2017-05-15T22-50-48Z_7f4985471eec402193310d836f37b9d9.zip](https://github.com/keeps/roda-in/files/1002686/roda-in_lang_enproperties_2017-05-15T22-50-48Z_7f4985471eec402193310d836f37b9d9.zip)
[roda-in_help_enproperties_2017-05-15T22-51-25Z_f70147be290e446286e57fe38e0cffd6.zip](https://github.com/keeps/roda-in/files/1002687/roda-in_help_enproperties_2017-05-15T22-51-25Z_f70147be290e446286e57fe38e0cffd6.zip)

**Comment by chalkos** [comment]
Thanks, that is very helpful.
By the way, do you know why there is a `lang.properties` and multiple `lang_<languageCode>.properties`? What is the purpose of the `lang.properties`?

**Comment by luis100** [comment]
I would assume to be the default file the [ResourceBundle](https://docs.oracle.com/javase/7/docs/api/java/util/ResourceBundle.html) reverts to in case an unsupported language is requested, but this should simply be a link to the English version. But it is just my guess, you should ask @hsilva-keep, @sleroux-keep or @adrapereira.

**Comment by chalkos** [comment]
An update on this:

- the updated resources `lang.properties` (most strings) and `help.properties` (help/documentation related strings) are on transifex
- it is impractical to use transifex with HTML files in our case so those will have to be translated the old fashioned way (by editing the file)
- the translations from transifex have been fetched and updated in roda-in

**Comment by chalkos** [comment]
Transifex can now be used to translate the files. Basically, when new strings are added, the main resource file needs to be uploaded (the new strings will be ready to be translated using the transifex website); when the translations have been updated, all (translation) files can be downloaded from transifex and overwritten in roda-in.

The CLI is not needed for this. Uploading the main resource file can be done on the website. Downloading all the translations is supported via the `ZIP` download button (which prepares a ZIP file and sends a link to your email).
