### ISSUE TITLE
It should be possible to activate/deactivate some SIP_TYPEs

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda-in#289]
- [ ] Configuration with ACTIVE SIP_TYPEs (defaults to Bagit & E-ARK)
- [ ] Replace all SIP_TYPE.values() by Controller.getActiveSipTypes (cache, lazy loaded)

**Comment by chalkos** [comment]
Since this is so close to the `SIPType` enum, I added the static method (to get the filtered `SIPType[]`) in there, as a better alternative to `.values()`.

activeSipTypes has eark and bagit by default, and also includes the hungarian sip 4 in the hungarian release.
