### ISSUE TITLE
When Alt+F4 is used to close modal windows, the application becomes unstable

### ISSUE THREAD

**Issue by chalkos** [keeps/roda-in#297]
Operating systems:
- Ubuntu
- (others?)

Steps to reproduce:

1. Open roda-in
2. Open the help window
3. Press Alt+F4

Note: all buttons are still working, the application is just greyed out. opening another modal window again and closing it via the `Close` button will revert the "greying out".

Images:

**before closing the modal window with Alt+F4:**
![image](https://cloud.githubusercontent.com/assets/98429/26545040/1a90f2c4-445c-11e7-8ff1-8bed888db444.png)

**after closing the modal window with Alt+F4:**
![image](https://cloud.githubusercontent.com/assets/98429/26545064/2d8ceaa4-445c-11e7-9050-6b0865059e34.png)

**Comment by luis100** [comment]
https://stackoverflow.com/a/42934330/1987075
