### ISSUE TITLE
NullPoinerException while creating E-ARK SIP

### ISSUE THREAD

**Issue by DenysShvorack** [keeps/roda-in#308]
I'm tying to create E-ARK SIP and getting NullPointerException.

![image](https://user-images.githubusercontent.com/7502095/27596617-bd677ab8-5b68-11e7-9d76-cb78f6c404e3.png)

After debugging the code I found the place where it occures. In the library org.roda-project:commons-ip:1.0.0 EARKSIP class in its build() method tries to give EARKMETSUtils.generateMETS() `ancestores` argument value as List containing one null.

```
MetsWrapper mainMETSWrapper = EARKMETSUtils.generateMETS(StringUtils.join(this.getIds(), " "), this.getDescription(), this.getType() + ":" + contentType, this.getProfile(), true, Optional.ofNullable(this.getAncestors()), (Path)null, this.getHeader());
```

As a result, code from generateMETS() does not work correctly:
```        
if(ancestors.isPresent() && !((List)ancestors.get()).isEmpty()) {
            StructMapType structMapParent = generateAncestorStructMap((List)ancestors.get());
            mets.getStructMap().add(structMapParent);
}
```

It goes inside the if, but it shouldn't. So either this part have to be changed or ancestores initialization has not lead into `Optional[[null]]`

In case reproduction details are needed:
![image](https://user-images.githubusercontent.com/7502095/27597566-67976122-5b6b-11e7-9cb2-d0c35119d1f2.png)

![image](https://user-images.githubusercontent.com/7502095/27597586-748f077c-5b6b-11e7-8193-7e8436a44210.png)

![image](https://user-images.githubusercontent.com/7502095/27597646-a278c344-5b6b-11e7-9298-a208cb675981.png)

**Comment by luis100** [comment]
@DenysShvorack thank you for your feedback, please check if this version solves the problem https://github.com/keeps/roda-in/releases/tag/v2.1.0-beta4

**Comment by DenysShvorack** [comment]
Update solved the problem for me, thanks.
