### ISSUE TITLE
NPE when adding a second metada scheme

### ISSUE THREAD

**Issue by beepsoft** [keeps/roda-in#316]
I use rodain-app-2.1.0-beta.7_OtherOS.jar on OSX El Capitan 10.11.6 (15G1217)

I do the followings:

1. In the INFORMATION PACKAGES window I click "new classification scheme"
2. In the FILE EXPLORER I open a folder
3. I move a single file from the file explorer to the information packages 
4. I select "One information package for each selected files or foelders"
5. I select "EAD 2002" in "Create new metadata from a template"
6. After Confirm I have a SIP with EAD 2002 metadata
7. I select the SIP and in the INSPECTOR I try to add Dublin core as metadata scheme using the + button next to the "EAD 2002" label. I get a null pointer exception like this:

<img width="1691" alt="screen shot 2017-09-01 at 14 21 02" src="https://user-images.githubusercontent.com/1926265/29969714-a64e89f6-8f21-11e7-87a8-75adefb79452.png">

This is the complete stack trace: [npe.txt](https://github.com/keeps/roda-in/files/1270186/npe.txt)

**Comment by beepsoft** [comment]
I found that I get the same exception doing the following as well:

1. In the INFORMATION PACKAGES window I click "new classification scheme"
2. In the INFORMATION PACKAGES window I click "Add"
3. I select "EAD 2002" in "Create new metadata from a template" and click "Continue":

<img width="2523" alt="screen shot 2017-09-01 at 14 46 24" src="https://user-images.githubusercontent.com/1926265/29970326-60d48f08-8f24-11e7-8617-8e4aef4a9bc5.png">

When I press OK and then "Cancel" in the "Add metadta" window, a node called "New node" is actually created despite the NPE.
  
<img width="1696" alt="screen shot 2017-09-01 at 14 45 07" src="https://user-images.githubusercontent.com/1926265/29970338-6a2579fa-8f24-11e7-83dd-40f41896835a.png">

**Comment by hsilva-keep** [comment]
Dear @beepsoft , I've confirmed as well that this bug happens. Thank you for reporting it. We'll solve it ASAP.

**Comment by luis100** [comment]
This issue no longer happens, it might have been fixed in previous releases but not documented here.
