### ISSUE TITLE
Information package association method to map the actual filesystem layout to SIP layout

### ISSUE THREAD

**Issue by beepsoft** [keeps/roda-in#318]
Hi,

Currently there are 4 ways to associate information packages to files/directories when added to the INFORMATION PACKAGES window:

<img width="801" alt="screen shot 2017-09-20 at 14 53 02" src="https://user-images.githubusercontent.com/1926265/30645201-3c144cd0-9e15-11e7-8cfa-86857ef78cfb.png">

I wonder if it was possible to add a new kind of association, which allows mapping a directory structure with mixed subdirectories and files while keeping the exact same structure as it was in the filesystem in the final SIP. The closest thing to this is the association type "One classification scheme from folder structure" but it requires a specific layout of directories and files.

For example, if I have a directory structure with files like this:

<img width="162" alt="screen shot 2017-09-20 at 15 01 55" src="https://user-images.githubusercontent.com/1926265/30645230-4a6b15b6-9e15-11e7-9fcd-6df07bdf77f5.png">

... and associate it with "One classification scheme from folder structure" the result is this:

<img width="313" alt="screen shot 2017-09-20 at 15 02 15" src="https://user-images.githubusercontent.com/1926265/30645237-56e282c0-9e15-11e7-9a49-700335842383.png">

Even though I had subdirectories these were turned into File entities with the files in the original directories as representations.

Instead I would like to have the directories mapped as eg. Collections or Subgroups and each individual file as a File with the actual file as its only representation.

Would it be possible to create such an association type?

**Comment by jmaferreira** [comment]
Dear Beep,

That's exactly what happens when you choose the option number 4.

<img width="808" alt="screen shot 2017-09-20 at 14 36 38" src="https://user-images.githubusercontent.com/3181302/30646525-3507a1ac-9e11-11e7-9a3f-d9e6526afc34.png">

However, instead of adding "Collections" it creates "Series".

**Comment by hsilva-keep** [comment]
@beepsoft I think the answer @jmaferreira gave you closes this issue. Do you agree?
