### ISSUE TITLE
E-ARK specific sip - tag missing

### ISSUE THREAD

**Issue by mezeijozsef** [keeps/roda-in#327]
According to E-ARK specification MIMETYPE tag should be in metadata.xml file, but it is not if I place a .siard file is inside the SIP.

**Comment by mezeijozsef** [comment]
correction: 

should be in **METS.xml** file,

**Comment by hsilva-keep** [comment]
@mezeijozsef First of all thank you for your feedback. 

Now answering to you: RODA-in and underneath library RODA Commons IP tries its best to defined the mimetype of the files being encoded in the package. It does that using Java code, for simplicity & performance matters, which is not perfect as you have discovered (by not setting .siard file mimetype; in my case, it sets it to **'application/zip'** ; for future reference, here's the direct pointer to the code handling that logic: https://github.com/keeps/commons-ip/blob/1_x/src/main/java/org/roda_project/commons_ip/utils/METSUtils.java#L151).

As an improvement, we will test mimetype detected by Java code and, if none has been detected, we'll set it to **'application/octet-stream'** at least to comply with E-ARK Common Specification for Information Packages.
