### ISSUE TITLE
Change the package icon from "black folder" to an actual "package"

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda-in#332]
<img width="1680" alt="Screenshot 2020-02-20 at 10 42 56" src="https://user-images.githubusercontent.com/3181302/74926522-ef839300-53cd-11ea-93a6-c9e98df49aa2.png">

**Comment by luis100** [comment]
https://fontawesome.com/v4.7/icon/archive

**Comment by luis100** [comment]
Fixed on https://github.com/keeps/roda-in/releases/tag/2.3.1
