### ISSUE TITLE
Question: Are there any CLI?

### ISSUE THREAD

**Issue by karatekaneen** [keeps/roda-in#343]
We are looking into an automated flow for creating SIPs and this package looks very promising. Although we would want to use a CLI or some other programmatic way to interact with roda-in.

Are there any available, and if so, are there any more information where we can see what's possible?

Best regards,
Robin

**Comment by luis100** [comment]
Programmatic creation of SIPs should be done using the base library: https://github.com/keeps/commons-ip

There isn't a proper CLI as the data model can be complex, but you can build one for your own purposes using the code example on the library README.
