### ISSUE TITLE
Cannot build from source, unauthorized to fetch commons-ip2 from Github Packages repository

### ISSUE THREAD

**Issue by prettyv** [keeps/roda-in#391]
When trying to compile RODA-In from source as documented in the README, maven fails to resolve all project dependencies and exits:
```
[ERROR] Failed to execute goal on project rodain: Could not resolve dependencies for project org.roda:rodain:jar:2.5.0: Failed to collect dependencies at org.roda-project:commons-ip2:jar:2.2.0: Failed to read artifact descriptor for org.roda-project:commons-ip2:jar:2.2.0: Could not transfer artifact org.roda-project:commons-ip2:pom:2.2.0 from/to github (https://maven.pkg.github.com/keeps/commons-ip): authentication failed for https://maven.pkg.github.com/keeps/commons-ip/org/roda-project/commons-ip2/2.2.0/commons-ip2-2.2.0.pom, status: 401 Unauthorized -> [Help 1]
```

I'm not familiar with GitHub Packages, could this package be configured to be world-accessible or alternatively (additionally?) published to Maven Central?

**Comment by prettyv** [comment]
I see now that GitHub Packages requires configuring a personal access token even for just installing packages from there. I believe it would be better and friendlier to have an alternative repository source for non-CI usage. I see you also have an Artifactory instance at `https://artifactory.keep.pt/ui/native/keep`, could this be used if Maven Central is not an option?

**Comment by luis100** [comment]
KEEP's artifactory is now used only for commercial plugins, and all packages are releases (Maven or other) are generally released into GitHub. Although the GitHub requirement for login is a bit of a hassle, it makes all publishing integrated and visible in the GitHub page, being it a Maven package, Debian package or other.
