### ISSUE TITLE
Create SIP automatically

### ISSUE THREAD

**Issue by jalshorji** [keeps/roda-in#397]
Is there a way to use roda-in as a library instead of using the UI. I want to automate the creation of the sip files.

**Comment by hmiguim** [comment]
Hi @jalshorji,

You can use [commons-ip](https://github.com/keeps/commons-ip) as a library to create and validate EARK-IP.

**Comment by hmiguim** [comment]
Commons-ip works as a library or a command line tool, it can fit different use cases.
