### ISSUE TITLE
Licensing question Oracle Java / OpenJDK

### ISSUE THREAD

**Issue by Tobbera** [keeps/roda-in#410]
Hi

I have a question regarding the Java environment used/required by the Roda-in application. 

When visiting the Roda-in webpage it tells me I have to download Java 8 to run the app. The link sends me to Oracle Java where I am shown information on the new (very expensive) licensing scheme that was instated in 2023 from Oracle's side. 

![image](https://github.com/keeps/roda-in/assets/12694196/249dd7ed-e2e7-4757-a7a2-c3544ab8566c)

Though, if I download the precompiled Windows EXE from Roda-in website it comes with Java bundled, and I don't have to install any Java separately to run Roda. The bundled Java seems to be OpenJDK, which in my understadning is free?

![image](https://github.com/keeps/roda-in/assets/12694196/f211c47f-e553-4055-88d9-b131b44162c1)

Can you please share some light on this?

Thanks in advance.

**Comment by luis100** [comment]
Hello. We use a free and open-source version of Java and already bundle it in the installer so to be easier for users.

The webpage information is outdated, I'll update it shortly.
