### ISSUE TITLE
Review the design on the tabs

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda-in#55]
Something like the attachment.

![screen shot 2015-12-10 at 17 31 13](https://cloud.githubusercontent.com/assets/3181302/11722988/ddfacce8-9f63-11e5-8766-8d810605b066.png)

**Comment by adrapereira** [comment]
Shouldn't this be in the RODA repo instead?

**Comment by jmaferreira** [comment]
Yes... sorry about that.
