### ISSUE TITLE
Allow to add documentation (i.e. arbitrary files) to the E-ARK SIP format

### ISSUE THREAD

**Issue by luis100** [keeps/roda-in#58]
Allow to add extra files into the SIP, attachments, that are not part of the data but that enrich it with contextual information that allows to more easily understand it. This should be an advanced option when adding metadata. There is a special place for this information in the EARK-SIP.

**Comment by hsilva-keep** [comment]
FYI,
RODA Commons IP fully supports, since alpha 4, E-ARK IP folder structure, which obviously includes the documentation folder (both IP and representaiton level).

**Comment by adrapereira** [comment]
Feature added.
