### ISSUE TITLE
.DS_Store files continue to show up on the interface

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda-in#70]
![screen shot 2016-01-14 at 14 56 01](https://cloud.githubusercontent.com/assets/3181302/12327535/0543c0a8-bacf-11e5-9555-110668406fba.png)

**Comment by adrapereira** [comment]
In the configuration file, replace "DS_STORE" with "DS_Store", restart the application and see if it works.

**Comment by jmaferreira** [comment]
Noup… did’t work.

**Comment by adrapereira** [comment]
Fixed.
