### ISSUE TITLE
Release two versions: PT and EN or add a way of changing the language of the UI (e.g. on startup for the first time)

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda-in#88]

**Comment by luis100** [comment]
The system language is used to ascertain the language to use, but can be overridden by configuration. This should be changeable on settings. No multiple releases are needed.

**Comment by jmaferreira** [comment]
Perfect.


Cumprimentos,
Miguel Ferreira

- -
Diretor executivo
KEEP SOLUTIONS, LDA.
Rua Rosalvo de Almeida, nº 5
4710-429 Braga, Portugal
W www.keep.pt E info@keep.pt
T +351 253066735 F +351 253067248
