### ISSUE TITLE
problems with java enviroment

### ISSUE THREAD

**Issue by tinezavr** [keeps/roda-in#97]
Could you help me out a bit. I downloaded jar version Beta 2.1. and tried to execute the exe file first, nothing happened. Then I switched to jar file, did as instructed, run in console and got the following  errors:

**java -jar rodain-app-1.0.0-beta.2.1.jar**

_2016-02-22 15:01:33,117 [JavaFX Application Thread] WARN  o.r.rodain.utils.LoggingOutputStream - Exception in Application start method_
_2016-02-22 15:01:33,120 [JavaFX Application Thread] WARN  o.r.rodain.utils.LoggingOutputStream - _
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - Exception in thread "main" java.lang.RuntimeException: Exception in Application start method_
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - _
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - 	at com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)_
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - _
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - 	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(Unknown Source)_
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - _
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - 	at java.lang.Thread.run(Unknown Source)_
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - _
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - Caused by: java.util.MissingResourceException: Can't find bundle for base name properties/lang, locale sl_SI_
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - _
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - 	at java.util.ResourceBundle.throwMissingResourceException(Unknown Source)_
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - _
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - 	at java.util.ResourceBundle.getBundleImpl(Unknown Source)_
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - _
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - 	at java.util.ResourceBundle.getBundle(Unknown Source)_
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - _
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - 	at org.roda.rodain.core.AppProperties.initialize(AppProperties.java:92)_
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - _
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - 	at org.roda.rodain.core.RodaIn.start(RodaIn.java:96)_
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - _
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - 	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(Unknown Source)_
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - _
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - 	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(Unknown Source)_
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - _
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - 	at com.sun.javafx.application.PlatformImpl.lambda$null$173(Unknown Source)_
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - _
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - 	at java.security.AccessController.doPrivileged(Native Method)_
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - _
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - 	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(Unknown Source)_
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - _
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - 	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)_
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - _
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - 	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)_
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - _
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - 	at com.sun.glass.ui.win.WinApplication.lambda$null$148(Unknown Source)_
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - _
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - 	... 1 more_
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - _
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - Caused by: java.lang.NullPointerException_
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - _
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - 	at org.roda.rodain.utils.FolderBasedUTF8Control.newBundle(FolderBasedUTF8Control.java:34)_
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - _
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - 	at java.util.ResourceBundle.loadBundle(Unknown Source)_
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - _
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - 	at java.util.ResourceBundle.findBundle(Unknown Source)_
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - _
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - 	at java.util.ResourceBundle.findBundle(Unknown Source)_
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - _
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - 	... 13 more_
_2016-02-22 15:01:33,124 [main] WARN  o.r.rodain.utils.LoggingOutputStream - _

I think it has something to do with enviroment. It has been a long time since I last used Java as development so any help is appriciated.

Test enviroment:
Windows 7 x64 (Slovenian)
Java 8.71 (build 1.8.0_71-b15)

**Comment by adrapereira** [comment]
Hello @tinezavr, thank you for the detailed question.
This happened because the application couldn't find the language resources for Slovenian. I thought it would fall back to English, but it doesn't. 
I'll work on a fix and notify you when it's ready.

**Comment by adrapereira** [comment]
@tinezavr I've released a new version with the fix. Let me know if you have any more problems.

**Comment by tinezavr** [comment]
Thank you, it works.



Od:     Andre Pereira <notifications@github.com>
Za:     keeps/roda-in <roda-in@noreply.github.com>, 
Kp:     Tine <tine.zavrsnik@gov.si>
Datum:  23.02.2016 11:07
Zadeva: Re: [roda-in] problems with java enviroment (#97)



@tinezavr I've released a new version with the fix. Let me know if you 
have any more problems.
?
