### ISSUE TITLE
When using the 3rd association option the application fails to deliver correct results

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda-in#98]
Various problems:

1. Not all files are listed on the middle panel (no Show more button)
2. If I select all items in the middle section and do a REMOVE. Not all folders are placed on the left pane
3. If I do a new project the application fails

**Comment by adrapereira** [comment]
The first and second points are known problems, the application only displays the first 100 SIPs created by an association rule. This will likely be solved in the next release (alpha4).
