### ISSUE TITLE
The validation of EAD3 is failing even though the document is valid on Oxygen

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda-in#99]
I guess its something to do with namespaces...

**Comment by PhillipTommerholt** [comment]
I don't know if it is of any interest or related. I tried last week to create a EAD3 file, and the normal xml-validator I use could not validate due to namespaces even though I could not find any flaws in it. I shifted xml-validator to Altova XMLSpy which was able to validate.

**Comment by jmaferreira** [comment]
Dear @PhillipTommerholt, it certainly appears to be related. Thanks.

**Comment by adrapereira** [comment]
@jmaferreira This is not a bug. The purpose of the validate button is to check if the metadata is a valid EAD2002 document. Validating an EAD3 document against the EAD2002 schema results in an error.

What we can do is change the validate button to:
 * Use the associated schema if the metadata was created using a template
 * Try to match the metadata to all the available schemas, when the metadata wasn't created using a template. This will slow down the process of SIP creation in those cases
 * When a metadata document cannot be matched to a known schema, hide the button.
